name: "build and push docker image"
on:
    workflow_dispatch:
        inputs:
            image_tag:
                type: choice
                description: "docker image tag"
                required: true
                options:
                    - develop
                    - release
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
    cancel-in-progress: true
permissions:
    contents: read
    packages: write
jobs:
    build:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - run: "echo 'image_name=${repo_name@L}' >> ${GITHUB_ENV}"
              env:
                  repo_name: ${{ github.repository }}
            - uses: docker/build-push-action@v6
              with:
                  platforms: linux/arm64
                  tags: ${{ env.image_name }}:${{ github.event.inputs.image_tag }}
                  push: true
