name: "📦"
run-name: ${{ inputs.image_tag }}
on:
    workflow_dispatch:
        inputs:
            image_tag:
                type: choice
                description: "docker image tag"
                required: true
                default: development
                options:
                    - development
                    - production
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}-${{ inputs.image_tag }}
    cancel-in-progress: true
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
jobs:
    build:
        name: "⚡️"
        runs-on: self-hosted
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4
            - uses: docker/metadata-action@v5
              id: meta
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: ${{ inputs.image_tag }}
            - uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - uses: docker/build-push-action@v6
              env:
                  DOCKER_BUILD_RECORD_UPLOAD: false
              with:
                  platforms: linux/arm64
                  tags: ${{ steps.meta.outputs.tags }}
                  push: true
